### ISSUE TITLE
Correct citation

### ISSUE THREAD

**Issue by ShelleyStall** [AGU-Data/DataCitationCoP#1]
Could you please change in the October post (third workshop): 
Stall, Shelley, Buck, Justin, Ayliffe, James, Agarwal, Deb, Coward, Caroline, & Erdmann, Chris. (2021, October 29). Data Citation Community of Practice - 29 October 2021 Workshop. Zenodo. https://doi.org/10.5281/zenodo.5641236

to

Stall, Shelley, Buck, Justin, Ayliffe, James, Stockhause, Martina, Agarwal, Deb, Coward, Caroline, & Erdmann, Chris. (2021, October 29). Data Citation Community of Practice - 29 October 2021 Workshop. Zenodo. https://doi.org/10.5281/zenodo.5641236

I corrected the authors but we didn't roll that back to the webpage. 

Thank you

**Comment by libcce** [comment]
Updated https://github.com/AGU-Data/DataCitationCoP/pull/2
